[package]
name = "contri-stump-vip"
version = "0.1.0"
authors = ["vipzero"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
transpose = "0.2.0"
chrono = "0.4.19"
